/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import model.Factura;

/**
 *
 * @author Usuario1
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        for (int i=100;i>=0;i--){
            cmbMetros.addItem(""+i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbMetros = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNeto = new javax.swing.JLabel();
        lblConsumo = new javax.swing.JLabel();
        lblAlcantarillado = new javax.swing.JLabel();
        lblExceso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("EMPRESA DE ACUEDUCTO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Metros cubicos consumidos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 260, -1));

        cmbMetros.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbMetros.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(cmbMetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 70, -1));

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 102));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Valor Consuno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Valor Alcantarillado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Valor Exceso:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Valor Neto:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        lblNeto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNeto.setForeground(new java.awt.Color(0, 0, 102));
        lblNeto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 120, 30));

        lblConsumo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConsumo.setForeground(new java.awt.Color(0, 0, 102));
        lblConsumo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 120, 30));

        lblAlcantarillado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAlcantarillado.setForeground(new java.awt.Color(0, 0, 102));
        lblAlcantarillado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblAlcantarillado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 120, 30));

        lblExceso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblExceso.setForeground(new java.awt.Color(0, 0, 102));
        lblExceso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblExceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gotaAgua.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 446, 423));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        int metros=Integer.parseInt(cmbMetros.getSelectedItem().toString());
        
        Factura factura = new Factura(metros);
        
        factura.consumo();
        double exceso = factura.exceso();
        double alcantarillado= factura.alcantarillado();
        factura.presenta(exceso, alcantarillado,lblConsumo,
                        lblAlcantarillado,lblExceso,lblNeto);
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbMetros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAlcantarillado;
    private javax.swing.JLabel lblConsumo;
    private javax.swing.JLabel lblExceso;
    private javax.swing.JLabel lblNeto;
    // End of variables declaration//GEN-END:variables
}
